### ISSUE TITLE
App redirects to "/ampache/" when installed as domain root

### ISSUE THREAD

**Issue by logomancer** [abeudin/ampache_ynh#15]
I tried installing this as the root on a domain using the Yunohost interface (eg: music.domain.tld).

When I went to music.domain.tld to access the app, it redirected to music.domain.tld/ampache/ and gave a 404 error. I suspect path configuration is still broken.

**Comment by stevenroose** [comment]
I do not get the redirect and I also installed on the root. Did you enter `/` as installation path during installation instead of the default `/ampache`?
If you entered `/ampache` and later promoted the app to "installed on the domain root" (using the button), it won't work.

But indeed, there are still things broken in the nginx config, especially for the API endpoints.

**Comment by logomancer** [comment]
Yes, I changed the path to '/' when I first installed the app, and got the redirection. I've scrutinized every config file I can think of, trying to fix it. Deleting the app and reinstalling has no effect.

I'm on 32-bit Debian jessie, if this helps.

**Comment by logomancer** [comment]
Upon further investigation, this appears to be an upstream bug, which I've filed. Closing.
